### ISSUE TITLE
Fix Buildbalancecard Container in Balance Section

### ISSUE THREAD

**Issue by patrick-codes** [EAshitey/my_mtn_app_clone#16]
Fix the balancecard container in balance section which overflows at the bottom

**Comment by patrick-codes** [comment]
I would like to work on this issue

**Comment by patrick-codes** [comment]
I made a pull request

**Comment by e-ashitey** [comment]
Great work
In your pull request always mention the issue number there so I can see what pull requests resolves what issue.
