### ISSUE TITLE
Remove the debug banner on the app

### ISSUE THREAD

**Issue by e-ashitey** [EAshitey/my_mtn_app_clone#8]
Hint: you can do this in main.dart.

**Comment by AtharvaNair04** [comment]
> Hint: you can do this in main.dart.

Hey this is my first time , can i do it?

**Comment by e-ashitey** [comment]
Sure you can go ahead.
Let me know once you are done. 
Remember to fork the repo, make the change and create a pull request to the dev branch.

**Comment by AtharvaNair04** [comment]
> Sure you can go ahead. Let me know once you are done. Remember to fork the repo, make the change and create a pull request to the dev branch.

I have created an MR for the issue. Please look into it.

**Comment by AtharvaNair04** [comment]
> Sure you can go ahead. Let me know once you are done. Remember to fork the repo, make the change and create a pull request to the dev branch.

Sorry i did it wrong the first time. This time i have created the pull request on the dev branch.

**Comment by e-ashitey** [comment]
That's great.
